version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: vektorspaco-multicam_nginx_1
      APP_PORT: 80

  nginx:
    image: nginx:alpine
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/content:/usr/share/nginx/html:ro
      - ${APP_DATA_DIR}/data/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: on-failure
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    depends_on:
      - nginx
